<?php

declare(strict_types=1);

namespace Wobqqq\Fortify\Services;

final readonly class SensitiveAdministratorLoginCheckerService
{
    public const LOGINS = [
        'admin', 'backend', 'administrator', 'root', 'superuser', 'sysadmin', 'system', 'manager', 'webmaster', 'support', 'test',
        'guest', 'demo', 'user', 'local', 'october', 'octobercms',
        'info', 'office', 'owner', 'host', 'master', 'server', 'security', 'service', 'operator', 'staff', 'help',
        'helpdesk', 'contact',
        'sales', 'marketing', 'billing', 'accounts', 'account', 'finance',
        'admin1', 'admin2', 'admin3', 'admin4', 'admin5', 'admin6', 'admin7', 'admin8', 'admin9', 'admin10',
        'admin11', 'admin12', 'admin13', 'admin14', 'admin15', 'admin16', 'admin17', 'admin18', 'admin19', 'admin20',
        'admin01', 'admin02', 'admin03', 'admin04', 'admin05', 'admin06', 'admin07', 'admin08', 'admin09',
        'admin123', 'admin1234', 'admin12345', 'admin123456', 'adminadmin',
        'administrator1', 'administrator2', 'administrator3', 'administrator4', 'administrator5',
        'administrator01', 'administrator02', 'administrator03',
        'superadmin', 'siteadmin', 'webadmin', 'mainadmin', 'paneladmin', 'portaladmin', 'consoleadmin',
        'root1', 'root2', 'root3', 'root123', 'rootadmin', 'rootuser', 'root01', 'root02',
        'sys', 'sys1', 'sysadmin1', 'sysadmin2', 'sysuser', 'systemadmin', 'systemuser', 'systemroot',
        'user1', 'user2', 'user3', 'user123', 'test1', 'test2', 'test3', 'testuser', 'testadmin',
        'guest1', 'guest2', 'demo1', 'demo2', 'demoadmin', 'demouser',
        'dev', 'dev1', 'dev2', 'developer', 'devadmin', 'devops', 'engineer', 'it', 'itadmin', 'network', 'networkadmin',
        'cloud', 'docker', 'kubernetes',
        'db', 'dbadmin', 'database', 'dba', 'mysql', 'postgres', 'oracle', 'sql', 'sqladmin',
        'ftp', 'ftpadmin', 'ftpuser', 'mail', 'mailer', 'postmaster', 'smtp', 'imap', 'pop3',
        'noreply', 'no-reply',
        'login', 'adminlogin', 'administratorlogin',
        'default', 'defaultadmin', 'defaultuser',
        'temp', 'temporary', 'trial', 'sample',
        'public', 'private', 'internal', 'external',
        'corp', 'corporate', 'company', 'companyadmin',
        'team', 'teamadmin', 'group', 'groupadmin',
        'main', 'primary', 'secondary',
        'localadmin', 'globaladmin', 'domainadmin', 'domain',
        'site', 'portal', 'gateway', 'console', 'access', 'auth', 'identity',
        'securityadmin', 'firewall', 'firewalladmin', 'audit', 'auditadmin',
        'compliance', 'complianceadmin',
        'policy', 'policyadmin',
        'vault', 'vaultadmin', 'secret', 'secrets',
        'token', 'tokenadmin', 'key', 'keyadmin', 'keys', 'keymaster',
        'cert', 'certificate', 'certadmin', 'ssl', 'ssladmin', 'tls', 'tlsadmin',
        'backup', 'backups', 'backupadmin',
        'monitor', 'monitoring', 'monitoradmin',
        'control', 'controlpanel', 'cpanel', 'plesk', 'hosting', 'hostmaster',
        'admin_dev', 'admin_test', 'admin_stage', 'admin_prod',
        'admin_local', 'admin_global', 'admin_main',
        'admin_it', 'admin_sys', 'admin_root',
        'admin_team', 'admin_group', 'admin_company',
        'admin_portal', 'admin_console', 'admin_gateway',
        'admin_security', 'admin_firewall', 'admin_audit',
        'admin_policy', 'admin_vault',
        'admin_key', 'admin_token',
        'admin_cert', 'admin_ssl',
        'admin_backup', 'admin_monitor',
        'stageadmin', 'stagingadmin', 'prodadmin', 'productionadmin', 'qaadmin', 'uatadmin',
        'consoleuser', 'gatewayuser', 'portaluser',
        'adminpanel', 'controlpaneladmin', 'paneluser',
        'web', 'web1', 'web2', 'webadmin', 'webuser',
        'service1', 'service2', 'serviceadmin',
        'operator1', 'operator2',
        'staff1', 'staff2',
        'help1', 'help2',
        'support1', 'support2', 'supportadmin',
        'contactadmin',
        'officeadmin',
        'manager1', 'manager2',
        'owneradmin',
        'serveradmin',
        'system1', 'system2', 'system3',
        'network1', 'network2',
        'cloudadmin',
        'dockeradmin',
        'kubeadmin',
        'dbuser',
        'sqluser',
        'mysqladmin',
        'postgresadmin',
        'oracleadmin',
        'mailadmin',
        'ftpmanager',
        'hostadmin',
        'siteowner',
        'siteuser',
        'sitecontrol',
        'panelcontrol',
        'panelmanager',
        'gatewaycontrol',
        'consolecontrol',
        'accesscontrol',
        'authcontrol',
        'identitycontrol',
    ];
}
